### ISSUE TITLE
Use array of objects

### ISSUE THREAD

**Issue by Wyzix33** [devbridge/Vanilla-Autocomplete#2]
Hi, is there any way to search in multiple properties of the object?
For example i have this object:

var o = "suggestions": [{ id : 1,value:"wash",extra:"new york"}, {id:2,value:"new",extra:"washington"}, ...]

can this script search in both value and extra for the input and display all results containing the query?

So if i search for wash or new the first 2 elements will be displayed because if i search for wash that is the first element value and it exists in the second element extra, same with new.

And also a maximum number of results i think will make things faster, so if i set it to 10 the script will stop searching after the maximum number of results was reached, and also keep the DOM smaller, because if i have 100.000 objects in my array and my first result is over 40.000 it will crash the browser when adding all the options, also nobody will look through 40k results, so a maximum limit will help.

Hope you understand and sorry for my English :)

Thanks

**Comment by tkirda** [comment]
If you implement your own `lookup` function, then you would have full control over how many items and what fields to search.
